trigger:
- main  # Or your default branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '20.11.0'  # Use the Node.js version you need
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install cypress
  displayName: 'Install dependencies'

- script: |
    npx cypress run
  displayName: 'Run Cypress tests'
