name: Cypress Docker Tests

on:
  pull_request:        # Run on every PR
 # schedule:            # Run nightly regression
 #   - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t cypress-tests .

      - name: Run Cypress tests
        run: docker run --rm cypress-tests
